### ISSUE TITLE
1.11.2 Bloomery GUI Update

### ISSUE THREAD

**Issue by Darkosto** [GlobbyPotato/Rockhounding_OreTiers#1]
Hello!

I've found an issue with GUI of the Bloomery block: The GUI only updates when the first operation is complete. 

Short video of the bug:
https://i.artdude.uk/darkosto/v3n9yiSU.mp4

Thanks for taking a look!
Darkosto

**Comment by GlobbyPotato** [comment]
Hi, uploaded an hotfix, it should work now.
