### ISSUE TITLE
Some recipes not showing up correctly in JEI

### ISSUE THREAD

**Issue by OreCruncher** [GlobbyPotato/Rockhounding_OreTiers#10]
Using crafttweaker to add recipes to some of the machines, like the coal refiner and drying pallet.  I indicate that the ore dictionary functionality be used when applying the recipe.  In JEI only a single items recipe is shown, though the device can accept the proper materials via the ore dictionary lookup.  Also, as a side effect, JEI will not know to consider the ore dictionary when a player attempts search/find recipes where the ingredient is used.

(I hope that made sense. :D)

**Comment by GlobbyPotato** [comment]
That should be due to the way the ingredients are grouped in jei handler. Will check it too.
