### ISSUE TITLE
[1.12.2] Bloomery crashes game when placed

### ISSUE THREAD

**Issue by teagan75** [GlobbyPotato/Rockhounding_OreTiers#12]
version: Rockhounding Mod: Ore Tiers 1.12.2-3.07
https://pastebin.com/f7NNv5a5

**Comment by GlobbyPotato** [comment]
hi, try updating the mod to v3.10 to see if it fixes, in case it is a sync issue with the core. 
I'll check it too when possible.

**Comment by teagan75** [comment]
Updating solved this. Thanks
