### ISSUE TITLE
Logs smelt into Coal Pellets instead of Charcoal Lumps

### ISSUE THREAD

**Issue by WenXin20** [GlobbyPotato/Rockhounding_OreTiers#3]
Forge v2316-1.10.2
Rockhounding: Ore Tiers v1.29
Unless this is supposed to be like this now, logs no longer smelt into charcoal lumps like it used to.

**Comment by GlobbyPotato** [comment]
It is not supposed to happen indeed, you should get charcoal lump, a bad enum kicked in. 
Uploaded v1.31 that should fix it back.

**Comment by WenXin20** [comment]
OK, thanks :
