### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Tellik** [GlobbyPotato/Rockhounding_OreTiers#4]
Is it possible to include the ability to add in custom items to allow input into the bloomery to melt down into bloom?

Specifically I would like to be able to add in iron clusters from Geolosys to be able to create bloom. I could also see the benefit from being able to add in other items, such as other mineral clusters that might have iron content and could be melted down for small amounts of bloom.

**Comment by GlobbyPotato** [comment]
Hi, you can use CraftTweaker to add custom recipes. Can specify the item to smelt, the resulting molten and the final ingot. Here is the example script: [LINK](https://github.com/GlobbyPotato/Rockhounding_OreTiers/blob/master/CraftTweaker_oretiers_script.zs)

**Comment by Tellik** [comment]
Oh, it has CraftTweaker support? That's amazing. Also, thank you for the quick response.
