### ISSUE TITLE
[Bug] Recipe for Coal to Lignite Coal in Basic Coal Refiner doesn't work proprelly

### ISSUE THREAD

**Issue by Fireztonez** [GlobbyPotato/Rockhounding_OreTiers#6]
Hello, I try the Basic Coal Refiner in my modpack to see how it work and what heat sourse it can support, and I found a bug, like you can see in the picture bellow, minecraft:coal in the refiner output minecraft:coal;

![coal-refiner-bug](https://user-images.githubusercontent.com/19277301/40283897-03dce70c-5c54-11e8-837c-57e005f53589.png)

But the Lignite coal to coal work;
![image](https://user-images.githubusercontent.com/19277301/40283974-fdf45e28-5c54-11e8-94e7-71643966197a.png)

Version: 
Minecraft 1.12.2
Forge: 14.23.3.2678
Rockhounding core: 3.0.8
Rockhounding core: 3.0.5

**Comment by GlobbyPotato** [comment]
Hi, are the coal variants oredicted all the same way (I see an "allCoal" and a "gemCoal")? The device is oredict sensible, so with the same key for all you are probably smelting everything into something else. You should obtain vanilla coal also from anthracite. If this is the case I can add a filter in the recipe to choose if oredict is to be considered.
