### ISSUE TITLE
Request: ability to add hammer types to the bloomery

### ISSUE THREAD

**Issue by belathus** [GlobbyPotato/Rockhounding_OreTiers#8]
I was thinking of adding extra hammer types to be used in the bloomery for converting the liquid bloom to ingots.

**Comment by GlobbyPotato** [comment]
it could be possible, but only for mining hammers because they need to be damageable, Will give it a look when possible.

**Comment by GlobbyPotato** [comment]
After some thinking, for now I'm discarding this request (but keeping it on hold for later eventually).
For how this mod is planned, it calls for overcomplicated mechanics than what it actually does. Not worth the tile ticking. If I'll rethink the bloomery concept will turn useful.

**Comment by belathus** [comment]
All good.
