### ISSUE TITLE
Drying pallet decrements by one regardless of input quantity

### ISSUE THREAD

**Issue by OreCruncher** [GlobbyPotato/Rockhounding_OreTiers#9]
I am using CraftTweaker to add some custom recipes for the drying pallet.  The case in question I wanted to add an input quantity > 1.  When the operation completes the input stack is decremented by 1 rather than the quantity specified on the input stack.

(I am putting together a modpack where leather is produced from other items using the drying pallet.  For example, I want to have 4 rabbit hides as input to produce 1 leather.)

**Comment by GlobbyPotato** [comment]
Hi, will give it a look soon. For now you can only set the drying time for each recipe, will try to make it also stacksize dependant.

**Comment by OreCruncher** [comment]
As an aside would it be possible to have interfaces accept ore dictionary objects as input rather than item stacks?  For example, if I wanted to add copper to the bloomery my script has to iterate over the ore dictionary collection adding them.  It seems it be more clean (and reliable I would think) if it were to specify <ore:oreCopper>.
